name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.4.2
      with:
        ref: v2.4.2

    - name: Install dependencies
      run: sudo apt-get -y install libgtk-3-dev xvfb

    - name: Start Xvfb
      run: |
        /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
        export DISPLAY=:99
      
    - name: Build and test application
      run: |
        gcc `pkg-config --cflags gtk+-3.0` -o main main.c `pkg-config --libs gtk+-3.0`
        xvfb-run -s "-screen 0 1024x768x24" ./main
