name: CI

on: [push]

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev x11-apps
        
      - name: Start Xvfb
        uses: peter-evans/xvfb-action@v1
        with:
          display: 99
          screen: 0
          resolution: 1920x1080x24
          
      - name: Build and Run
        run: |
          gcc main.c -o main `pkg-config --cflags gtk+-3.0` `pkg-config --libs gtk+-3.0`
          export DISPLAY=:99
          ./main
