name: Keyboard Ninja

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Build
      run: gcc -o main main.c
      
    - name: Language Choice Test
      run: echo -e "1\nhello\nq\n" | timeout 10s ./key
      # Проверяем, что программа корректно обрабатывает ввод пользователем языка и слова
      
    - name: Results Test
      run: echo -e "1\nhello\nworld\nq\n" | timeout 10s ./key > output.txt && cat output.txt | grep 'Точность'
      # Проверяем, что программа корректно выводит результаты игры
