name: Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libgtk-3-dev -y

    - name: Build
      run: gcc main.c -o main `pkg-config --libs --cflags gtk+-3.0`

    - name: Test
      run: |
        xvfb-run -a ./main &
        sleep 5
        xdotool type "test"
        xdotool key Return
        sleep 5
        xdotool type "test"
        xdotool key Return
        sleep 5
        xdotool type "test"
        xdotool key Return
        sleep 5
        xdotool key Control+c
        wait
