name: Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      DISPLAY: ":99"

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev xdotool
        sudo apt-get install -y xvfb

    - name: Build
      run: gcc main.c -o main `pkg-config --libs --cflags gtk+-3.0`

    - name: Test
      run: |
        Xvfb :99 -screen 0 1024x768x24 &
        export DISPLAY=:99
        sleep 5
        xdotool type "test"
        xdotool key Return
        sleep 5
        xdotool type "test"
        xdotool key Return
        sleep 5
        xdotool type "test"
        xdotool key Return
        sleep 5
        xdotool key Control+c
        wait
