name: CI

on: [push]

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev xvfb
      
    - name: Build the program
      run: |
        gcc -o main main.c `pkg-config --cflags --libs gtk+-3.0`
        
    - name: Run the program with xvfb
      run: |
        xvfb-run --no-sandbox -a ./main
