name: CI

on: [push]

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev x11-apps
          export DISPLAY=:99

      - name: Start Xvfb
        uses: hermit-x/start-xvfb@v1
        with:
          params: -screen 0 1920x1080x24
        
      - name: Build and Run
        run: |
          gcc main.c -o main `pkg-config --cflags gtk+-3.0` `pkg-config --libs gtk+-3.0`
          ./main
