name: CI

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev xvfb
      
    - name: Start Xvfb
      run: |
        Xvfb :0 -screen 0 1024x768x16 -ac &
        sleep 5
        export DISPLAY=:0.0
        
    - name: Build the program
      run: |
        gcc -o main main.c `pkg-config --cflags --libs gtk+-3.0`
        
    - name: Run the program in Xvfb
      run: |
        xvfb-run -a ./main
